server {
    listen 80;
    root /usr/share/nginx/html;

    location /prontuario/ {
        alias /usr/share/nginx/html/prontuario/;
        try_files $uri $uri/ /prontuario/index.html;
    }

    location /prontuario-dev/ {
        alias /usr/share/nginx/html/prontuario/;
        try_files $uri $uri/ /prontuario-dev/index.html;
    }
}
